<a href="https://colab.research.google.com/github/Rabbi627-maker/data-analyst-parcours/blob/main/01_tips_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1
La consigne demande : De lire le fichier avec read_csv et de trouvé son shape

Prédictions : fichier.shape()

pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
(244, 7)

In [1]:
import pandas as pd

In [2]:
fichier = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [3]:
fichier.shape

(244, 7)

Q2

la consigne demande : head(3) et tail(3) : combien de lignes chacun ?


ils vont contenir trois lignes chacun

In [4]:
fichier.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [5]:
fichier.tail(3)

     total_bill   tip     sex smoker   day    time  size
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

Q3

la consigne demande : Créer la colonne addition par personne et quelle valeur j'attends a la ligne

Au niveau de la premiere ligne une nouvelle colonne est créer et on obtient 8.495

In [6]:
fichier['addition_par_personne'] = fichier['total_bill'] / fichier['size']

In [7]:
fichier.head()

   total_bill   tip     sex smoker  day    time  size  addition_par_personne
0       16.99  1.01  Female     No  Sun  Dinner     2               8.495000
1       10.34  1.66    Male     No  Sun  Dinner     3               3.446667
2       21.01  3.50    Male     No  Sun  Dinner     3               7.003333
3       23.68  3.31    Male     No  Sun  Dinner     2              11.840000
4       24.59  3.61  Female     No  Sun  Dinner     4               6.147500

Q4

La question demande : Garder les lignes avec adittion strictement supérieure a 10

je ne peux prédire il y'a  trop de ligne je vais écrire le code

In [8]:
fichier[(fichier['addition_par_personne'] ) > 10].shape

(49, 8)

Partie B

j'attends un shape (2,2)

In [9]:
import io
texte = "2017-01-01,100\n2017-01-02,105\n2017-01-03,103"

In [10]:
texte1 = pd.read_csv(io.StringIO(texte))

In [11]:
texte1.shape

(2, 2)

Q7 après ca le shape donne (3,1)

In [12]:
texte1 = pd.read_csv(io.StringIO(texte), header=None, names=['date', 'prix'], index_col='date')

In [13]:
texte1.shape

(3, 1)